# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            AI Club
tagline:          'IIIT-Bangalore'
description:      '<a href="https://www.iiitb.ac.in/" target="_blank">IIIT-Bangalore</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'IIIT-B AI Club'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/sknadig/iiitb_ai_club
